name: "Improve Lyrics Sync-Type"
description: "Lyrics that don't have the best Sync-Type. Ex., having Line lyrics when they should be Karaoke."
title: "First Songs' Name // Artists"
labels: ["Improve Lyrics Sync"]
assignees: surfbryce

body:
  - type: checkboxes
    id: "pre-checklist"
    attributes:
      label: "Before you list your Songs:"
      options:
        - label: "IF you have multiple songs you want to report, have the title mention after the first Songs' Name/Artists that there are multiple, adding \", ...\" is good enough."
          required: true
        - label: "For every song you want to report, check Musixmatch or Apple Music and check to see if the Sync Type is better than what Beautiful Lyrics has."
          required: true
  - type: textarea
    id: "song-links"
    attributes:
      label: "List Song Links"
      description: "For each song, copy its link, and then list each one numerically."
      placeholder: |
        1. https://open.spotify.com/track/1FkNQCYnaSvTPqXjpsB13X
        2. https://open.spotify.com/track/4xjjaT7yDpZ6jDRZXBHxM4
        3. https://open.spotify.com/track/2YcPBBa0K32C429HT77RT0