name: Song has Incorrect Lyrics
description: ''
title: 'Song Name // Song Artists'
labels: ['Incorrect Lyrics']

body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Missing Lyrics Checklist
      description: Please check off the following items before submitting your missing lyrics report.
      options:
        - label: 'IF you just have one song, put the song name and artist in the Bug Report Title ("Song Name // Song Artists") and then for the contents of your bug-report, link to what the lyrics SHOULD be'
          required: true
        - label: 'IF you have multiple songs you want to report, have the title mention that there are multiple songs with incorrect lyrics. For the contents of your bug-report, you should list every song by their name and who it is by ("Song Name // Song Artists"), with every song also linking to what the lyrics SHOULD be'
          required: true

  - type: textarea
    id: song-and-artist-names
    attributes:
      label: Song and Artist Names
      description: 'Please list the song names and who they are by in a list. Each list item should be in this format: "Song Name // Song Artists"'
      placeholder: |
        Song Name // Song Artists
        Song Name // Song Artists
        Song Name // Song Artists
