name: "Incorrect Lyrics Timing"
description: "Lyrics that are significantly delayed (early or late) from their respective Songs."
title: "First Songs' Name // Artists"
labels: ["Incorrect Lyrics Timing"]
assignees: surfbryce

body:
  - type: checkboxes
    id: "pre-checklist"
    attributes:
      label: "Before you list your Songs:"
      options:
        - label: "IF you are reporting multiple songs, add \", ...\" to the end of your title."
          required: true
  - type: textarea
    id: "song-links"
    attributes:
      label: "List Song Links"
      description: "For each song, copy its link, and then list each one numerically."
      placeholder: |
        1. https://open.spotify.com/track/1FkNQCYnaSvTPqXjpsB13X
        2. https://open.spotify.com/track/4xjjaT7yDpZ6jDRZXBHxM4
        3. https://open.spotify.com/track/2YcPBBa0K32C429HT77RT0