name: "Suggestion"
description: "Use this to Suggest New Features, Improvements, and etc."
title: "Summarize your Suggestion Here"
labels: ["Suggestion"]
assignees: surfbryce

body:
  - type: dropdown
    id: "suggestion-type"
    attributes:
      label: "What are you Suggesting?"
      multiple: false
      options:
        - a Feature
        - an Improvement
    validations:
      required: true
  - type: textarea
    id: "suggestion-reason"
    attributes:
      label: "What is the context behind this Suggestion?"
      description: "What led you to think of this Suggestion? Was it a problem/pain-point with Beautiful Lyrics? Was it something you experienced somewhere else? And etc."
    validations:
      required: true
  - type: textarea
    id: "suggestion"
    attributes:
      label: "What is your Suggestion?"
      description: "**IF you *can*, please provide visual examples/references like Screenshots/Video of what you are thinking/talking about!**"
    validations:
      required: true
  - type: checkboxes
    id: "explanation-checklist"
    attributes:
      label: "Suggestion Checklist"
      description: "Make *SURE* you followed all of the below, if not, your Suggestion WILL be **DELETED**."
      options:
        - label: "You clearly titled/explained your Suggestion."
          required: true
        - label: "You accurately described/contextualized the reasoning behind your Suggestion."
          required: true
        - label: "IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting."
          required: true